### PR TITLE
Correct init_zeal.cpp

### PR DESCRIPTION
**Pull request by ghost**
Rm-885 is "zeal_row" and RM-887 is "Lumia 720T"

### CODE REVIEW

**Review by sjrmac — COMMENTED** [review]
It was already perfect when I looked at it in settings as a test. No need to correct it really....

**Comment by ghost** [comment]
It can work but the names have to be corrected. If you do not think so, check out LumiaFirmware or my closed pull request in the fame device tree.

**Comment by sjrmac** [comment]
What do you mean by 'they have to be corrected' ?

**Comment by ghost** [comment]
I mean the codename for RM-885 was "zeal_row" and RM-887 was the Lumia 720T (chinese variant).

**Comment by sjrmac** [comment]
zeal_row is the generic one and just "zeal" should be kept somehow. I am aware that zeal_cmcc is the Chinese variant or lumia 720T

**Comment by ghost** [comment]
On LumiaFirmware there is no reference to a non-chinese version of RM-887: http://www.lumiafirmware.com/ser/RM-887

**Comment by sjrmac** [comment]
yeah, i am aware of this, we need to keep zeal along with the others if possible. i'll try some stuff then probably just copy your work in

**Comment by ghost** [comment]
closed

**Pull request closed without merging**
