### PR TITLE
Make Wi-Fi working

### PR DESCRIPTION
**Pull request by ghost**
-Removal of the creation of a symlink
-WCNSS_qcom_wlan_nv.bin added and automatically pushed to /system/ build dir
=================================================================
Minor changes:
-GMS identifier changed to android-nokia
-Minor corrections for init library, you are replacing it, so feel free not to merge this

### CODE REVIEW

**Comment by feherneoh** [comment]
Check my branch, these are mostly done there. Thanks for the GMS change, I'll use that.

**Comment by ghost** [comment]
The guys from @cm-nokia-x2 also did that.
Since @gabixdev has written that the X2 uses the same camera as Lumia 520, 525 and 1320, your team could port the camera wrapper from them but it seems like they are using they are using a diffrent camera driver.
I have also updated your LK flasher to make it more noob-friendly.
-Automatic detection for the processor architecture
-You can choose if you want to install TWRP for Lumia 520/525 or Lumia 720
I would recommend you to check if I did something wrong.
[Link](https://drive.google.com/open?id=0B8kEP4oexvxkNmVVLW44cThqaU0)

**Comment by feherneoh** [comment]
As long as it's not posted by me, and I don't have to deal with the consequences of new bugs, I don't really want to check it. I'll do that later, or if something is dangerously broken.
I'll add that GMS change to the new device tree, and look into camera after the new kernel is mostly working.

**Comment by ghost** [comment]
@feherneoh What a new kernel?


_Sent from my Motorola Moto G4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
Since this configuration is proprietary, I will move this to a vendor tree.

**Pull request closed without merging**
